const COMMONS = Object.freeze({
	ASN_SERIAL_PATTERN: /AS[MN][1-2][UBR][AB][0-9]{4}/,
	BOOSTER_PORT_NUM: 7,
	MAX_DIFFUSING_DURATION_MS: 10000,
	BASIC_UNIT_BLOWING_DURATION_MS: 501,
	MINIMUM_BLOW_CONTROL_TIME_MS: 100
});

module.exports = COMMONS;